version: "3"
services:
  db:
    image: mysql:5.7
    ports:
     - "3306:3306"
    volumes:
     - /var/lib/mysql
    # for docker-compose
    #restart:
    #   always
    environment:
     - MYSQL_ROOT_PASSWORD=orange17
     - MYSQL_DATABASE=mydatabase
  bolt:
    image: rossriley/docker-bolt:3.2
    # for docker-compose
    # network_mode: bridge
    environment:
     - BOLT_EXT=bolt/theme-2016 dev-master
     - BOLT_TITLE=My Bolt Site
     - BOLT_THEME=bolt/theme-2016
     - BOLT_DIR_MODE=0755
     - BOLT_CACHE_DIR=cache
    volumes:
     - ./app/extensions:/var/www/html/app/extensions
     - ./app/cache:/var/www/html/app/cache
     - ./core:/var/www/html/core
     - ./app/database:/var/www/html/app/database
     - ./public:/var/www/html/public
     - ./public/themes:/var/www/html/public/themes
     - ./public/files:/var/www/html/public/files
     - ./public/views:/var/www/html/public/views
     - ./public/uploads/thumbs:/var/www/html/public/uploads/thumbs
  web:
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    # for external dockerfile when working with docker-compose
    #build:
    #  context: .
    #  dockerfile: ./Dockerfile
    image: marcosfreitas/lamp_boltcms:develop
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      restart_policy:
        condition: on-failure
    # for docker-compose
    #links:
    # - db
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
